[package]
name = "ml-project"
version = "0.1.0"
edition = "2021"

[dependencies]
linfa = "0.6.0"
linfa-trees = "0.6.0"
linfa-datasets = { version = "0.6.0", features = ["iris"] }
ndarray = "0.15.6"
csv = "1.1"
